var os_markers = [
{
'id':1,
'title':'Burley Bar Stone',
'location':'Inside main entrance of Leeds Building Society, The Headrow Leeds 1',
'unveiler':'Lord Marshall of Leeds, President of Leeds Civic Trust,  former Leader of Leeds City Council',
'date':'27 Nov 1987',
'sponser':'Leeds & Holbeck Building Society',
'easting':430055,
'northing':433766,
'caption':'This stone, now housed inside the main entrance of Leeds Building society marked the medieval boundary between the manorial borough, or town, of Leeds and Leeds Main Riding, the surrounding agricultural land. First recorded 1726.'
},
{
'id':2,
'title':'Louis Le Prince (1st Plaque)',
'location':'British Waterways, Leeds Bridge, Lower Briggate, Leeds 1',
'unveiler':'Mr. William Le Prince Huettle, great-grandson of Louis Le Prince',
'date':'13 Oct 1988',
'sponser':'British Waterways Board',
'easting':430296,
'northing':433148,
'caption':'Louis Aime August Le Prince came to Leeds in 1866 where he experimented in cinematography. In 1888 he patented a one-lens camera which he filmed Leeds Bridge from the British Waterways building. These were probably the world&rsquo;s first successful moving pictures.'
},
{
'id':3,
'title':'Louis Le Prince (2nd Plaque)',
'location':'BBC Studios, Woodhouse Lane, Leeds 2',
'unveiler':'Sir Richard Attenborough, Actor, Broadcaster and Film Director',
'date':'14 Oct 1988',
'sponser':'British Broadcasting Corporation',
'easting':0,
'northing':0,
'caption':'Not found'
},
{
'id':4,
'title':'Temple Mill ',
'location':'Marshall Street, Leeds 11',
'unveiler':'Mr Bruce Taylor',
'date':'14 Feb 1989',
'sponser':'Kay & Company Ltd',
'easting':429559,
'northing':432749,
'caption':'The magnificent but highly functional flax spinning mill to your left was erected by John Marshall, founder of the Leeds flax industry.  Joseph Bonomi modelled the mill and this office building (added in 1843) on the Egytian temple at Edfu.  Erected in 1838-40.'
},
{
'id':5,
'title':'18 Park Place',
'location':'18 Park Place, Leeds 1',
'unveiler':'Sir Christopher Benson, Chairman, MEPC plc',
'date':'24 Feb 1989',
'sponser':'MEPC plc',
'easting':429533,
'northing':433600,
'caption':'This house, restored to its former grandeur by MEPC plc in 1988, is situated in one of the most elegant streets of Georgian Leeds. Merchants and gentlemen were attraced here by the beautiful view of the river and neighbouring hills.'
},
{
'id':6,
'title':'The Victoria Hotel',
'location':'Great George Street, Leeds 1',
'unveiler':'Mr John Power MBE, Deputy Lord Lieutenant of West Yorkshire',
'date':'25 Apr 1989',
'sponser':'Joshua Tetley & Sons Ltd',
'easting':429750,
'northing':433920,
'caption':'Was Built in 1865 to serve people attending the Assize Courts newly held at Leeds Town Hall. Its Stylish accommodation then comprised spacious dining rooms and bars, a billiard room, private sitting rooms and 28 bedrooms.'
},
{
'id':7,
'title':'The Assembly Rooms',
'location':'Crown Street, Leeds 2',
'unveiler':'Mr Bettison (Senior)',
'date':'27 Apr 1989',
'sponser':'Mr Bruce Bettison, then Owner of Waterloo Antiques',
'easting':430456,
'northing':433362,
'caption':'Its Handsomely decorated ballroom and card rooms made it one of Yorkshire&rsquo;s finest assembly rooms. Its patrons were the Leeds merchants and the local nobility and gentry. The ground floor formed the Northern range of the third white Cloth Hall. Opened 9th '
},
{
'id':8,
'title':'Kemplay’s Academy',
'location':'Nash’s Tudor Fish Restaurant, off New Briggate, Leeds 1',
'unveiler':'Mr. Lawrence Bellhouse, Proprietor, Nash’s Tudor Fish Restaurant',
'date':'May 1989',
'sponser':'Lawrence Bellhouse,  Proprietor, Nash’s Tudor Fish Restaurant ',
'easting':430290,
'northing':433880,
'caption':'This fine house built in 1720 for Matthew Wilson is shown on John Cossin&rsquo;s plan of Leeds in 1725. In 1817 Richard Kemplay purchased the property to house his &rsquo;Academy for Young Gentlemen.&rsquo;'
},
{
'id':9,
'title':'Brodrick’s Buildings',
'location':'Cookridge Street, Leeds 2',
'unveiler':'Mr John M. Quinlan, Director, Trinity Services',
'date':'20 Jul 1989 ',
'sponser':'Trinity Services (Developers)',
'easting':429914,
'northing':434054,
'caption':'These fine shops and offices were designed by Cuthbert Brodrick (1822-1905) the architect of Leeds Town Hall and the Corn Exchange and the Mechanics&rsquo; Institute. They were renvovated by Trinity Services in 1988. ERECTED 1864'
},
{
'id':10,
'title':'The West Bar',
'location':'Bond Street Centre, Boar Lane, Leeds 1',
'unveiler':'Councillor J.L. Carter, Lord Mayor of Leeds',
'date':'19 Sept 1989',
'sponser':'Bond Street Shopping Centre Merchants’ Association',
'easting':429999,
'northing':433396,
'caption':'The bar stone making the western boundary of the built-up area of the medieval town of Leeds stood here. Scarcely a single building lay in the old manorial park to the West of this point before 1758.'
},
{
'id':11,
'title':'Park Square',
'location':'45 Park Square, Leeds 1',
'unveiler':'Mr. Anthony Blackmore, Senior Partner, Simpson Curtis, Solicitors',
'date':'21 Sept 1989',
'sponser':'Simpson Curtis Solicitors',
'easting':429668,
'northing':433744,
'caption':'This elegant square formed part of the Wilson family&rsquo;s plan to create a high-class residential estate on the site of the medieval park of the Manor of Leeds. Its residents were merchants, clergy, lawyers and surgeons. Built 1788-1810'
},
{
'id':12,
'title':'Leeds Manor House',
'location':'Scarborough Hotel Bishopsgate Street,    Leeds 1 ',
'unveiler':'Professor Maurice Beresford, , Doyen of Leeds Historians.',
'date':'26 Sept 1989',
'sponser':'Joshua Tetley & Sons Ltd',
'easting':429978,
'northing':433320,
'caption':'The Medieval manor house stood here on &rsquo;Castle Hill.&rsquo; Its deep moat looped between the river and Boar Lane. Richard Wilson lavishly rebuilt it in 1765 and in 1821 it became Henry Scarebrough&rsquo;s hotel. The present-day pub is a survivng extension.'
},
{
'id':13,
'title':'St Paul’s House',
'location':'St Paul’s House, Park Square, Leeds 1',
'unveiler':'Mr K.E. Reynolds, Branch Manager of the Fire Society',
'date':'3 Oct 1989',
'sponser':'Norwich Union Insurance Group',
'easting':429582,
'northing':433674,
'caption':'This building was originally a warehouse and cloth-cutting works built for John Barran, the founder of the mass-production, ready-made clothing industry in Leeds. Barran was a Mayor of Leeds and served as its Liberal M.P. from 1876-1885. Architect: Thomas Ambler. Erected 1878'
},
{
'id':14,
'title':'Leeds Charity School',
'location':'Mark Lane, Leeds 2',
'unveiler':'Professor Neville Rowell, Vice-President, Leeds Civic Trust',
'date':'30 Oct 1989',
'sponser':'Professor Neville Rowell, Vice-President, Leeds Civic Trust',
'easting':430210,
'northing':433820,
'caption':'The Chapel of Harrison&rsquo;s almshouses which formerly occupied this site, was converted for use by the charity school in 1726. When the present building was erected in 1815, the institution clothed 80 poor girls and trained them for domestic service. Founded 1705'
},
{
'id':15,
'title':'Hotel Metropole',
'location':'King Street, Leeds 1',
'unveiler':'Lord Strathclyde, Minister for Tourism',
'date':'10 Nov 1989',
'sponser':'Crown Hotels',
'easting':429715,
'northing':433462,
'caption':'The fine hotel designed by Chorley, Connon and Chorley is one of the best examples of terracotta work in Leeds. A remarkable feature is the large stone cupold taken from the town&rsquo;s fourth elite Cloth Hall (erected in 1868) which formerly occupied this site. Opened 1899.'
},
{
'id':16,
'title':'Yorkshire Penny Bank',
'location':'Yorkshire Bank plc, Infirmary Street, Leeds 1',
'unveiler':'Mr. David Mortimer, Controller (Marketing), Yorkshire Bank',
'date':'1 Feb 1990',
'sponser':'Yorkshire Bank plc',
'easting':429820,
'northing':433550,
'caption':'This famous bank, later known as Yorkshire bank, was founded in Leeds in 1856. These flamboyant premises, designed by G. B. Bulmer, were opened in 1894. the first purpose-built Leeds general Infirmary (1771) formerly stood on this site.'
},
{
'id':17,
'title':'William Hey&rsquo;s House',
'location':'Albion Place, Leeds 1',
'unveiler':'Private unveiling',
'date':'March 1990',
'sponser':'Leeds Law Society',
'easting':430080,
'northing':433609,
'caption':'This impressive Georgian townhouse was built for William Hey (1736-1819) one of the founders and later Chief Surgeon of Leeds General Infirmary. For 50 years Hey was in the front rank of British surgeons. Architect: Thomas Johnson, Erected 1794-5.'
},
{
'id':18,
'title':'Leeds Infirmary',
'location':'Leeds General Infirmary, Great George Street, Leeds 1',
'unveiler':'Professor Neville Rowel MD, FRCP, Vice-President, Leeds Civic Trust',
'date':'12 Mar 1990',
'sponser':'Medical Faculty of the General Infirmary at Leeds',
'easting':429750,
'northing':433970,
'caption':'This General Infirmary moved here from Infirmary Street in 1869. The building, designed by George Gilbert Scott, incorporated ideas from Florence Nightingale. The plan placed it  the foremost rank of European Hospitals.'
},
{
'id':19,
'title':'Leeds School of Medicine',
'location':'Thoresby Place, Leeds 1',
'unveiler':'Professor M.S. Losowsky, Dean of the Faculty of Medicine and Professor of Medicine, The University of Leeds',
'date':'3 Apr 1990',
'sponser':'Faculty of Medicine, University of Leeds',
'easting':429560,
'northing':434080,
'caption':'The institution founded in 1831, was one of the first provincial medical schools in England. The move here from Park Street in 1894 provided the school with its second purpose-built premises. Architect: W.H. Thorp. Erected: 1891-94'
},
{
'id':20,
'title':'Queens Court',
'location':'Queens Court, Lower Briggate, Leeds 1',
'unveiler':'Mr. Brian Prideaux, Property Developer',
'date':'2 May 1990',
'sponser':'Brian Prideaux, Property Developer',
'easting':430276,
'northing':433294,
'caption':'The historic courtyard occupies one of the 60 burgage plots which abutted Briggate in the Middle Ages. It is fronted by an eight-bayed woollen cloth merchant&rsquo;s house (built c.1714) and contains the merchant&rsquo;s cloth finishing shop and warehouses.'
},
{
'id':21,
'title':'Leeds & Liverpool Canal Warehouse',
'location':'Canal Basin, Water Lane, Leeds 11',
'unveiler':'Mr. Len Davis,  Leeds Canal Basin (Development) Ltd',
'date':'3 May 1990',
'sponser':'Len Davis, Leeds Canal Basin (Development) Ltd',
'easting':429841,
'northing':433038,
'caption':'In 1777 this robust stone building was constructed as a terminal warehouse for the Leeds Liverpool Canal. Started in 1770, the Canal was finally completed in 1816 at a cost of £1,200,00 nearly five times the original estimate.'
},
{
'id':22,
'title':'Bank of England',
'location':'South Parade, Leeds 1',
'unveiler':'Councillor Les Carter, Lord Mayor of Leeds',
'date':'11 May 1990',
'sponser':'Bank of England',
'easting':429927,
'northing':433752,
'caption':'The Bank of England opened a branch in Leeds in 1827. These premises, entered from South Parade, were designed by Philip Hardwick and erected 1862-64. The Bank remained on this site until moving to King Street in 1971.'
},
{
'id':23,
'title':'A.S.L.E. & F.',
'location':'The Commercial Inn, Sweet Street, Leeds 11',
'unveiler':'Mr. Derrick Fullick, General Secretary, A.S.L.E. & F.',
'date':'17 Jan 1991',
'sponser':'A.S.L.E. & F.',
'easting':429584,
'northing':432558,
'caption':'The Associated Society of Locomotive Engineers and Firemen was founded in 1880. Because of the convenience and importance of Leeds as a railway centre, the Society established its first registered office here at the Commercial Inn, Sweet Street in 1881.'
},
{
'id':24,
'title':'The Great Synagogue',
'location':'Belgrave Street, Leeds 2',
'unveiler':'Rabbi Dr Solomon Brown',
'date':'3 Feb 1991',
'sponser':'The United Hebrew Congregation',
'easting':430290,
'northing':433990,
'caption':'In 1860 the first purpose-built synagogue in Yorkshire since the expulsion of the Jews from England in 1290 was erected here. Until 1983 it served the Jewish Community, which had settled in the Leylands (between North Street and Regent Street) in the 19th Century'
},
{
'id':25,
'title':'Mill Hill Chapel and Joseph Priestley',
'location':'Mill Hill Chapel, corner of Park Row and City Square, Leeds 1',
'unveiler':'Mrs Eila Forrester, President of the General Assembly of Victorian and Free Christian Churches',
'date':'28 Mar 1991',
'sponser':'Leeds & Holbeck Building Society',
'easting':429955,
'northing':433467,
'caption':'This elegant Gothic building designed by Bowman and Crowthern in 1848, replaced the original 17th century chapel. Its Congregation formerly Presbyterian, now Unitarian-dates from 1672. Joseph Priestley, LL.D, F.R.S., discoverer of oxygen, was minister here 1767-1773.'
},
{
'id':26,
'title':'The Church Institute',
'location':'Albion Place, Leeds 1',
'unveiler':'Private unveiling',
'date':'91',
'sponser':'The British Deaf Association',
'easting':430135,
'northing':433604,
'caption':'The power house behind the advancement of religious and secular education on the principles of the Church of england in Leeds, and the home for a host of Church organisations. The British Deaf Association was founded here on 24th July 1890. Erected 1866-68'
},
{
'id':27,
'title':'Coloured Cloth Hall',
'location':'Cloth Hall Court, Infirmary Street, Leeds 1',
'unveiler':'Mr D.F.L. Sykes, Senior Partner Hepworth & Chadwick, Solicitors',
'date':'16 May 1991',
'sponser':'Hepworth & Chadwick, Solicitors',
'easting':429843,
'northing':433528,
'caption':'This plaque has been removed. The circle where it once was is visible.'
},
{
'id':28,
'title':'Fairbairn House',
'location':'71 Clarendon Road, Leeds 2',
'unveiler':'Col. Alan Roberts, Pro-Chancellor, University of Leeds',
'date':'20 Jun 1991',
'sponser':'University of Leeds',
'easting':428987,
'northing':434329,
'caption':'Originally known as Woodsley House, this monumental villa was built in 1840 for Sir Peter Fairbairn, the textile engineering magnate, and mayor of Leeds 1858-59. Queen Victoria stayed here in 1858 when she came to open the Town Hall.'
},
{
'id':29,
'title':'Atkinson Grimshaw',
'location':'56 Cliff Road, Hyde Park, Leeds 6',
'unveiler':'Dr Tony Moyes at the request of Mrs Sandra Wood, great-granddaughter of Atkinson Grimshaw',
'date':'18 Jul 1991',
'sponser':'Members of the Grimshaw family and North Hyde Park Neighbourhood Association',
'easting':0,
'northing':0,
'caption':''
},
{
'id':30,
'title':'John Harrison',
'location':'St John’s Churchyard Wall New Briggate, Leeds 1',
'unveiler':'Professor Neville Rowell, Vice-President of Leeds Civic Trust',
'date':'29 Aug 1991',
'sponser':'Professor Neville Rowell, Vice-President, Leeds Civic Trust',
'easting':430270,
'northing':433810,
'caption':'(1579-1656) St John&rsquo;s, one of England&rsquo;s most remarkable churches was built by this celebrated benefactor in 1634. A cloth merchant and co-founder of Leeds corporation, he further endowed the town with almshouses, a new grammar school and a market cross.'
},
{
'id':31,
'title':'White Cloth Hall',
'location':'Crown Street, Leeds 1',
'unveiler':'Mr D.J. Houghton, Managing Director, Speciality Shops plc',
'date':'24 Sept 1991',
'sponser':'Speciality Shops plc',
'easting':430412,
'northing':433354,
'caption':'This superbly restored gateway belonged to the magnificent quadrangular market hall which underpinned the prosperity of Georgian Leeds. Merchants and 1300 West Riding clothiers met here on Tuesdays and Saturdays to trade in undyed &rsquo;White&rsquo; woollen cloth.'
},
{
'id':32,
'title':'Joshua Tetley',
'location':'The Brewery Gates, Hunslet Road, Leeds 10',
'unveiler':'Mr Charles Tetley, Great-grandson of Joshua Tetley',
'date':'29 Jan 1992',
'sponser':'Joshua Tetley & Sons',
'easting':430365,
'northing':433042,
'caption':'Joshua Tetley (1778-1859) In 1822, Joshua Tetley bought William Sykes Brewery business which had stood here since 1792. Joshua&rsquo;s enterprise and fine quality ales created a reputation which for ovwer 150 years made the name Tetley&rsquo;s synonymous with the city of Leeds.'
},
{
'id':33,
'title':'Ralph Thoresby, FRS',
'location':'15 Kirkgate, Leeds 2',
'unveiler':'Mr Arthur Elton, President of The Thoresby Society',
'date':'6 Oct 1992',
'sponser':'The Thoresby Society',
'easting':430329,
'northing':433518,
'caption':'(1658-1725) The Historian of Leeds had his home and museum here.'
},
{
'id':34,
'title':'Arthur Ransome',
'location':'6 Ash Grove, Leeds 6',
'unveiler':'Mr Norman Willis, General Secretary of the Trades Union Congress and longstanding member of the Arthur Ransome Society',
'date':'2 Mar 1993',
'sponser':'Arthur Ransome Society',
'easting':0,
'northing':0,
'caption':''
},
{
'id':35,
'title':'Aire & Calder Navigation',
'location':'Riverside Court, Call Lane, Leeds 1',
'unveiler':'Mr. Norman Stubbs, Chief Executive, Tay Homes',
'date':'20 Apr 1993',
'sponser':'Tay Homes and British Waterways',
'easting':430344,
'northing':433226,
'caption':'Before the railway age, the making navigable of the River Aire importantly made Leeds an inland port connected directly to Hull. Cheap water carriage was vital for the successful export of the cloth marketed and finished in the town. Opened 1700.'
},
{
'id':36,
'title':'North-Eastern Railway Viaduct',
'location':'Swinegate end of the Viaduct, Leeds 1',
'unveiler':'Mr. Gerald Egan, Leeds City Station Manager',
'date':'27 Apr 1993',
'sponser':'Leeds Corporation and British Rail’s Community Unit',
'easting':430108,
'northing':433235,
'caption':'This 1500 yard viaduct, including the New Station (now known as City Station) built over the river and canal, is one of the great feats of Victorian civil engineering. It linked railway termini on opposite sides of Leeds. Erected 1866-69.'
},
{
'id':37,
'title':'Tower Works',
'location':'Tower Works, Globe Road, Leeds 12',
'unveiler':'Mr Martin Eagland, Chief Executive, Leeds Development Corporation',
'date':'25 May 1993',
'sponser':'Leeds Development Corporation',
'easting':0,
'northing':0,
'caption':'Not found'
},
{
'id':38,
'title':'Samuel Smiles (1812-1905)',
'location':'Leeds Institute & Civic Theatre, Cookridge Street, Leeds 2',
'unveiler':'Mr J. Olav Arnold, President, Leeds Civic Trust',
'date':'29 Mar 1994',
'sponser':'Leeds & Holbeck Building Society',
'easting':429921,
'northing':434027,
'caption':'The great propagandist of Victorian values through his books, &rsquo;Self-help&rsquo;, &rsquo;Character&rsquo;, &rsquo;Thrift&rsquo;, and &rsquo;Duty,&rsquo; inspired by his lectures to Leeds working men in 1845. He worked in Leeds 1838-58 as a newspaper editor, doctor and then railway secretary.'
},
{
'id':39,
'title':'Fletland Mills',
'location':'42, The Calls, Leeds 2',
'unveiler':'Mr Keith Roberts, Secretary, The Bransby Agricultural Trading Association',
'date':'25 May 1994',
'sponser':'Leeds Development Corporation and Jonathan Wix, the owner of 42 The Calls',
'easting':430526,
'northing':433259,
'caption':'In 1887 Wright Bros., corn millers, acquired these late 18th and 19th century mills. They produced large quantities of flour and &rsquo;horse corn&rsquo; for the Leeds district. In 1991 the buildings were splendidly converted to a high quality hotel.'
},
{
'id':40,
'title':'Joseph Aspdin',
'location':'Packhorse Yard, between Lands Lane and Briggate, Leeds 1',
'unveiler':'Sir George Mosley, Chairman, British Cement Association and    National Civic Trust',
'date':'21 Oct 1994',
'sponser':'British Cement Association',
'easting':430166,
'northing':433580,
'caption':'Portland Cement, one of mankind&rsquo;s most important manufactured materials, was patented by Joseph Aspdin, a Leeds Bricklayer, on 21 October 1824. Aspdin lived in this yard (then called Slip Inn Yard) and first sold his cement in Angel Inn Yard'
},
{
'id':41,
'title':'Yorkshire Ladies’ Council of Education',
'location':'18 Blenheim Terrace, Leeds 2',
'unveiler':'The Lady Grimthorpe DCVO, Past President, Yorkshire Ladies’ Council of Education',
'date':'2 Mar 1995',
'sponser':'Mr & Mrs Peter Hartley, Hillards Charitable Trust',
'easting':0,
'northing':0,
'caption':'Was founded in 1876 to promote the education of girls and women and occupied this building between 1928-1988. It served as an administrative centre for Council activities and housed The Yorkshire Ladies&rsquo; Secretarial College.'
},
{
'id':42,
'title':'St Aidan’s Church',
'location':'St Aidan’s Church, Roundhay Road, Leeds 8',
'unveiler':'Mr Noel Squires',
'date':'23 Apr 1995',
'sponser':'Mr Noel Squires, Landlord of the New Roscoe Inn',
'easting':0,
'northing':0,
'caption':''
},
{
'id':43,
'title':'East Bar',
'location':'Leeds Parish Church, Kirkgate, Leeds 2',
'unveiler':'Professor Neville Rowell. Vice-President of Leeds Civic Trust',
'date':'23 May 1995',
'sponser':'Professor Neville Rowell',
'easting':430700,
'northing':433329,
'caption':'This ancient stone marked the Eastern boundary of the medieval town of Leeds.'
},
{
'id':44,
'title':'Sir Leonard Hutton',
'location':'On wall of the house at 5 Fulneck, Pudsey, Leeds 28',
'unveiler':'Sir Lawrence Byford, President of Yorkshire County Cricket Club',
'date':'14 Oct 1995',
'sponser':'Yorkshire County Cricket Club',
'easting':0,
'northing':0,
'caption':''
},
{
'id':45,
'title':'Leeds College of Art',
'location':'Leeds College of Art, Vernon Street, Leeds 2',
'unveiler':'Sir Alan Bowness, former Director of The Henry Moore Foundation and former Director The Tate Gallery, son-in-law of Barbara Hepworth.',
'date':'5 Mar 1996',
'sponser':'The Henry Moore Foundation',
'easting':429959,
'northing':434039,
'caption':'Founded in 1846, by Leeds Mechanics&rsquo; and Literary Institution, pioneered the teaching of practical art design in England and USA. Henry Moore and Barbara Hepworth studied here. This building was erected for the college in 1903.'
},
{
'id':46,
'title':'First Leeds Synagogue',
'location':'Merrion Centre, Leeds 2',
'unveiler':'Councillor Malcolm Bedford, Lord Mayor of Leeds',
'date':'8 Dec 1996',
'sponser':'Mr Edward Ziff, Town Centre Securities',
'easting':430134,
'northing':433973,
'caption':'This plaque was erected to commemorate the 150th anniversary of the opening of the first Leeds synagogue in 1846 in a converted house near this site in Back Rockingham Street.'
},
{
'id':47,
'title':'City Varieties Music Hall',
'location':'The City Varieties, Swan Street, Leeds 1',
'unveiler':'Mr Paul Daniels, Magician and TV celebrity',
'date':'27 Mar 1997',
'sponser':'Friends of the City Varieties',
'easting':430216,
'northing':433716,
'caption':'Harry Landler, Charlie Chaplin and Houdini performed in this music hall built in 1865 for Charles Thornton on the site of the white swan coaching inn. Famous venue of the Good Old Days, 1st broadcast in 1953.'
},
{
'id':48,
'title':'Central Higher Grade School',
'location':'2 Great George Street, Leeds 1',
'unveiler':'Councillor Suzi Armitage, Chair of Community Benefits & Rights Committee of Leeds City Council.',
'date':'16 Sept 1997',
'sponser':'Leeds City Council',
'easting':430010,
'northing':433950,
'caption':'This imposing school was erected by Leeds School board as the town&rsquo;s first local authority secondary school. Renamed City of leeds School in 1928, it merged with Thoresby High School in 1972, and moved to a new site in 1994. Opened 1889.'
},
{
'id':49,
'title':'Leeds Union Workhouse',
'location':'Thackray Medical Museum, Beckett Street, Leeds 9',
'unveiler':'Mr. Paul Thackray, Founder, Thackray Medical Museum',
'date':'11 Feb 1998',
'sponser':'Thackray Medical Museum',
'easting':0,
'northing':0,
'caption':''
},
{
'id':50,
'title':'Oakwood Clock',
'location':'498 Roundhay Road, Leeds 8',
'unveiler':'Sir James Savile, TV Celebrity and local resident',
'date':'7 Apr 1998',
'sponser':'William H Brown Estate Agents',
'easting':0,
'northing':0,
'caption':''
},
{
'id':51,
'title':'Golden Acre Park',
'location':'On the outside wall of the café in Golden Acre Park at Otley Road, Leeds 16',
'unveiler':'Professor Neville Rowell, Vice-President, Leeds Civic Trust',
'date':'25 Aug 1998',
'sponser':'Professor Neville Rowell, Vice-President, Leeds Civic Trust',
'easting':0,
'northing':0,
'caption':''
},
{
'id':52,
'title':'Leeds Burial Ground',
'location':'Opposite  St. James’s Hospital, Beckett Street, Leeds 9',
'unveiler':'Mrs Sylvia Barnard, Founder, Friends of Beckett Street Cemetery',
'date':'11 Sept 1998',
'sponser':'Mr & Mrs David Kaye, Publishers of the Funeral Services Journal',
'easting':0,
'northing':0,
'caption':''
},
{
'id':53,
'title':'Leeds School Board',
'location':'Civic Court, Calverley Street, Leeds 1',
'unveiler':'Councillor Graham Kirkland, Lord Mayor of Leeds',
'date':'2 Oct 1998',
'sponser':'The Rushbond Group',
'easting':429804,
'northing':433862,
'caption':'Erected this fine headquarters and examination centre in 1878 - 81. First elected by the ratepayers of Leeds in 1870, the board built sufficient schools to ensure that for the first time every child in Leeds received an elementary education.'
},
{
'id':54,
'title':'Moortown Golf Club',
'location':'1 plaque on the Clubhouse and 1 on the  entrance gates at Mootown Golf Club, Harrogate Road, Leeds 17',
'unveiler':'Mr Malcolm Tain, Club Captain',
'date':'11 Feb 1999',
'sponser':'Moortown Golf Club',
'easting':0,
'northing':0,
'caption':''
},
{
'id':55,
'title':'Bank Mills',
'location':'Rose Wharf, East Street, Leeds 9',
'unveiler':'Mr Gordon Carey RIBA, Chairman of Carey Jones Architects',
'date':'12 Mar 1999',
'sponser':'Caddick Developments and Carey Jones, Architects',
'easting':0,
'northing':0,
'caption':''
},
{
'id':56,
'title':'Queen’s Arcade',
'location':'Briggate end of Queen’s Arcade, Leeds 1',
'unveiler':'Councillor Keith Wakefield, Chair, Leeds City Council Development Service Group Committee',
'date':'28 Mar 1999',
'sponser':'DTZ Debenham Thorpe',
'easting':430248,
'northing':433653,
'caption':'Named in honour of Queen Victoria&rsquo;s Golden Jubilee. Built in 1888-9 by Armistead and Proctor on the site of the Rose and Crown coaching inn which occupied one of Briggate&rsquo;s medieval burgage plots. Architect: Edward Clark.'
},
{
'id':57,
'title':'Meanwood Tannery',
'location':'Mill Pond Road, Off Monkbridge Road, Meanwood, Leeds 6',
'unveiler':'Mr Fred Casperson and Mr Arthur Hopwood, distinguished local historians',
'date':'17 July 1999',
'sponser':'Country & Metropolitan Homes Northern Ltd',
'easting':0,
'northing':0,
'caption':''
},
{
'id':58,
'title':'Burmantofts Pottery',
'location':'Gargrave Court, off Gargrave Approach, Leeds 9',
'unveiler':'Mr. George Mudie, MP',
'date':'10 Dec 1999',
'sponser':'Bramall Construction',
'easting':0,
'northing':0,
'caption':''
},
{
'id':59,
'title':'Potternewton Mansion',
'location':'Potternewton Mansion, Harehills Lane, Leeds 7',
'unveiler':'Mr. Fabian Hamilton, MP',
'date':'1 Oct 1999',
'sponser':'Park Lane College',
'easting':0,
'northing':0,
'caption':''
},
{
'id':60,
'title':'Victoria Quarter',
'location':'Victoria Quarter, between Vicar Lane and Briggate, Leeds 1',
'unveiler':'Councillor Keith Parker, Lord Mayor of Leeds',
'date':'02-May-00',
'sponser':'The Prudential Insurance Company',
'easting':430335,
'northing':433640,
'caption':'Was begun in 1900 with the opening of Frank Matcham&rsquo;s splendid County and Cross arcades. Enhanced by covering Queen Victoria&rsquo;s Street, the site was formerly medieval yards, Georgian shambles and slaughter houses. Leeds 2000.'
},
{
'id':61,
'title':'William Congreve',
'location':'Bardsey Grange, Cornmill Lane, Bardsey, Leeds 17',
'unveiler':'Mrs Bridget Ely (nee Congreve) and Councillor David Congreve, relatives of William Congreve',
'date':'08-Jul-00',
'sponser':'Councillor David Hudson who represents Wetherby District on Leeds City Council',
'easting':0,
'northing':0,
'caption':''
},
{
'id':62,
'title':'Leeds Town Hall (Millennium Blue Plaque) ',
'location':'Inside  the Calverley Street entrance of the Town Hall, Leeds 1',
'unveiler':'Councillor Bernard Atha OBE, Lord Mayor of Leeds',
'date':'27-Nov-00',
'sponser':'Professor Neville Rowell, Vice-President, Leeds Civic Trust',
'easting':429787,
'northing':433866,
'caption':'This greatest of monuments to Victorian municipal government was opened by Queen Victoria on 7 September 1858. Its architect, Cuthbert Brodrick, created a civic palace with courts, council chamber, mayor&rsquo;s parlour, offices, bridewell and concert hall, the'
},
{
'id':63,
'title':'Kirkgate Market',
'location':'Vicar Lane end of Butchers’ Row, Kirkgate Market, Leeds 2',
'unveiler':'Mr. Richard Wainwright, formerly Liberal MP for Colne Valley',
'date':'14-Dec-00',
'sponser':'Richard Wainwright',
'easting':430467,
'northing':433539,
'caption':'In 1826 the Leeds Vicaridge and Croft were purchased to create a fruit, vegetable and cattle market. An elegant Crystal Palace-style covered market was erected in 1857, followed in 1904 by today&rsquo;s magnificent market hall designed by Leeming & Leeming.'
},
{
'id':64,
'title':'Montague Burton',
'location':'Hudson Road, Leeds 9',
'unveiler':'Mr Arnold Burton and Mr Raymond Burton, the twin sons of Sir Montague Burton',
'date':'30 Mar 2001',
'sponser':'The Burton Family',
'easting':0,
'northing':0,
'caption':''
},
{
'id':65,
'title':'Kirkstall Brewery',
'location':'Broad Road, Leeds 5',
'unveiler':'Private unveiling',
'date':'1',
'sponser':'Leeds Metropolitan University',
'easting':0,
'northing':0,
'caption':''
},
{
'id':66,
'title':'Cliff Tannery',
'location':'Near the entrance to Sugarwell Court, Meanwood Road, Leeds 7',
'unveiler':'Private unveiling',
'date':'1',
'sponser':'Leeds Metropolitan University',
'easting':0,
'northing':0,
'caption':''
},
{
'id':67,
'title':'The Philosophical Hall',
'location':'HSBC Bank, Park Row, Leeds 1',
'unveiler':'Dr Peter Evenett, President Leeds Philosophical and Literary Society',
'date':'28 Jun 2001',
'sponser':'Leeds Philosophical and Literary Society',
'easting':429922,
'northing':433523,
'caption':'The imposing home of the Leeds Philisophical and Literary Society stood here until 1966. erected in 1821, it became the centre of scientific and cultural life in Leeds housing a fine museum conveyed to the City in 1921.'
},
{
'id':68,
'title':'Smithfield Ironworks',
'location':'90 – 94, North Street Leeds 2',
'unveiler':'Councillor David Hudson, Lord Mayor of Leeds',
'date':'15 Jul 2001',
'sponser':'Road Roller Association',
'easting':430590,
'northing':434110,
'caption':'Built as the Smithfield Hotel in the 1860&rsquo;s to serve Leeds cattle Market opposite, it later became the imposing frontage of Thomas Green at Son Ltd. Green made steam and motor rollers, traction engines, steam trams, railway locomotives and grass cutting machines.'
},
{
'id':69,
'title':'The Grange',
'location':'Beckett Park, Leeds 16',
'unveiler':'Private unveiling',
'date':'Oct-01',
'sponser':'Leeds Metropolitan University',
'easting':0,
'northing':0,
'caption':''
},
{
'id':70,
'title':'Permanent House',
'location':'Brown’s Restaurant, 19The Light’, The Headrow, Leeds 1',
'unveiler':'Dr. Arnold Ziff, OBE A former President of the Leeds Permanent Building Society',
'date':'16 Jan 2002',
'sponser':'Brown’s Restaurant',
'easting':429941,
'northing':433804,
'caption':'Was built on the newly created Headrow in 1930 as the headquarters of Leeds Permanent Building Society. Its grandeur befitted Leeds&rsquo; greatest financial institution which from 1848 enabled generations to fulfil the dream of buying their own home. Architect G.W.Atkinson.'
},
{
'id':71,
'title':'Ellen Heaton',
'location':'Swarthmore Education Centre, 6 Woodhouse Square, Leeds 3',
'unveiler':'Ms. Rommi Smith Poet, performer and teacher.',
'date':'27 Feb 2002',
'sponser':'Friends of Swarthmore Education Centre and  Little Woodhouse Community Association',
'easting':429314,
'northing':433990,
'caption':'Lived in 6 Woodhouse Square from 1859-94. She was an influential Pre-Raphaelite art patron and an active campaigner for women&rsquo;s rights, education, health, environmental issues and anti-vivisection. Her friend, the poet Christina Rossetti, stayed here.'
},
{
'id':72,
'title':'Leeds Civic Hall',
'location':'Millennium Square, Portland Crescent, Leeds 1',
'unveiler':'Mr. George Williamson, apprentice joiner, who worked on the construction of the Civic Hall',
'date':'10 Jun 2002',
'sponser':'Leeds City Council',
'easting':429864,
'northing':434086,
'caption':'Was erected 1930-33 by the unemployed accomodation, includes Lord mayor&rsquo;s ceremonial rooms, Council Chamber, committee rooms and offices. It was built to serve the &rsquo;ever expanding municipal functions and duties&rsquo; of Leeds City Council. Architect: Vincent H'
},
{
'id':73,
'title':'E J Arnold& Son Ltd',
'location':'3, Lower Briggate, Leeds 1',
'unveiler':'Mr. J. Olav Arnold and Mr.  Martin Arnold, great-grandsons of Edward James Arnold',
'date':'3 Jul 2002',
'sponser':'J. Olav Arnold and Family',
'easting':430237,
'northing':433243,
'caption':'Britain&rsquo;s leading educational suppliers and printers was established in this Georgian merchant&rsquo;s house No.3 Briggate in 1870. Its warehouse and factory was in Blayd&rsquo;s yard.'
},
{
'id':74,
'title':'Leeds Grammar School',
'location':'Moorland Road Leeds 6',
'unveiler':'Councillor Bryan North, Lord Mayor of Leeds with pupils Sam Best and Daniel Saffer',
'date':'7 Oct 2002',
'sponser':'Leeds Grammar School',
'easting':429030,
'northing':434740,
'caption':'Was founded in 1552 by Wiliam Sheafield, chantry priest, Leeds Parish Church. It Occupied this building from 1859 to 1997. Famous pupils include; John Smeaton, engineer, G. Studdert Kennedy, &rsquo;Woodbone Willie&rsquo;, chaplain; John Ireland, composer; Field Marsh.'
},
{
'id':75,
'title':'John Deakin Heaton',
'location':'19Claremont’, 23 Clarendon Road, Leeds 2',
'unveiler':'Professor Maurice Beresford, Emeritus Professor of Economic History, Leeds University.',
'date':'30 Oct 2002',
'sponser':'Yorkshire Archaeological Society and Mrs I. A. J.  Moses',
'easting':429228,
'northing':434093,
'caption':'Eminent physician lived at Claremont a Georgian merchant&rsquo;s villa, from 1856 -80 he was a prime mover in the campaign for Leeds Town Hall, and played major roled in the development of the Leeds General Infirmary and the Yorkshire College, later the University of Leeds.'
},
{
'id':76,
'title':'Sir Berkeley Moynihan (1865-1936)',
'location':'33 Park Square, Leeds 1',
'unveiler':'Dr C. B. Wynn Parry, grandson of Sir Berkeley Moynihan',
'date':'27 Jan 2003',
'sponser':'The Faculty of the  General Infirmary at Leeds',
'easting':429555,
'northing':433764,
'caption':'Inspirational teacher and pioneer in abdominal surgery had his consulting rooms here from 1893-1930. He introduced the wearing of rubber gloves and prized &rsquo;caressing the tissues&rsquo; rather than speed in surgery. President of the Royal College of Surgeons 1920&rsquo;s.'
},
{
'id':77,
'title':'Samuel Ledgard',
'location':'Nelson Inn, Armley Road, Leeds 12',
'unveiler':'Councillor Michael Fox, Deputy Lord Mayor of Leeds',
'date':'15 Apr 2003',
'sponser':'Samuel Ledgard Society and the  Ledgard Family',
'easting':0,
'northing':0,
'caption':''
},
{
'id':78,
'title':'Frank Kidson',
'location':'5 Hamilton Avenue,  Leeds 7',
'unveiler':'Dr Vic Gammon, Chairman of Frank Kidson Memorial Fund and Senior Lecturer in Popular & World Music, Leeds University.',
'date':'20 May 2003',
'sponser':'Frank Kidson Memorial Fund',
'easting':0,
'northing':0,
'caption':''
},
{
'id':79,
'title':'Mann’s Patent Steam Cart & Wagon Company Ltd',
'location':'Pepper Road, Hunslet, Leeds 10',
'unveiler':'Councillor Neil Taggart, Lord Mayor of Leeds',
'date':'15 Jun 2003',
'sponser':'The Leeds & District Traction Engine Club',
'easting':0,
'northing':0,
'caption':''
},
{
'id':80,
'title':'Yorkshire Patent Steam Wagon Company',
'location':'Pepper Road, Hunslet Leeds 10.',
'unveiler':'Councillor Neil Taggart, Lord Mayor of Leeds',
'date':'15 Jun 2003',
'sponser':'The Leeds & District Traction Engine Club',
'easting':0,
'northing':0,
'caption':''
},
{
'id':81,
'title':'Newton House',
'location':'54, Spencer Place Leeds 7',
'unveiler':'Mrs. Jean White, former Deputy Lord Mayor of Leeds',
'date':'10 Sept 2003',
'sponser':'Angel Group plc',
'easting':0,
'northing':0,
'caption':''
},
{
'id':82,
'title':'The Hunslet Engine Company',
'location':'125 Jack Lane, Hunslet, Leeds 10',
'unveiler':'Councillor Neil Taggart, Lord Mayor of Leeds',
'date':'21 Sept 2003',
'sponser':'Don Townsley, a former executive of the Company',
'easting':0,
'northing':0,
'caption':''
},
{
'id':83,
'title':'Dewhirst’s and Marks & Spencer',
'location':'Harper Street, Leeds 2',
'unveiler':'Mr. Timothy Dewhirst, Deputy Lord Lieutenant of the East Riding of Yorkshire, Chairman of DewhirstGroup Ltd, and great-grandson of Mr. Isaac Dewhirst?',
'date':'21 Oct 2003',
'sponser':'Urban Edge Group',
'easting':430535,
'northing':433416,
'caption':'This was the warehouse of Isaac Dewhirst, wholesale haberdasher and manufacturer of hoisery, pinafores, underclothing and aprons. Obtaining supplies here, the polish immigrant pedlar, Michael Marks, met Dewhirst&rsquo;s cashier Tom Spencer. In 1894 they formed the Department Store Marks & Spencers.'
},
{
'id':84,
'title':'Bardon Hill Stables (Access only on foot around security gates)',
'location':'Weetwood Lane,  Leeds 16',
'unveiler':'Mrs. Jacky Banyard,  Sales and Marketing Director, CALA Homes (Yorkshire) Ltd.',
'date':'20 Nov 2003',
'sponser':'CALA Homes (Yorkshire) Ltd',
'easting':0,
'northing':0,
'caption':''
},
{
'id':85,
'title':'Cookridge Hall',
'location':'Cookridge Lane, Leeds16',
'unveiler':'Mr. Don Cole, Cookridge Historian',
'date':'28 Nov 2003',
'sponser':'Trustees of Kirke’s Charity, Esporta Health and Fitness Club, and Leeds City Council.',
'easting':0,
'northing':0,
'caption':'Inspirational teacher and pioneer in abdominal surgery had his consulting rooms here from 1893-1930. He introduced the wearing of rubber gloves and prized &rsquo;caressing the tissues&rsquo; rather than speed in surgery. President of the Royal College of Surgeons 1920&rsquo;s'
},
{
'id':86,
'title':'Sir John Barran MP',
'location':'Joseph’s Well, Hanover Walk, Leeds 3.',
'unveiler':'Mr. Brian Walker, former Leader of Leeds City Council',
'date':'4 Dec 2003',
'sponser':'J Pullan & Sons Ltd',
'easting':429384,
'northing':433946,
'caption':'Pioneered the leeds ready made clothing industry ubn the 1850s, introducing the band knife for cutting multiple layers of cloth. In 1887 he this factory to his others in Park Square. As mayor he secured the purchase of Roundhay Park for Leeds.'
},
{
'id':87,
'title':'The Middleton Railway',
'location':'Moor Road Station, Hunslet, Leeds 10',
'unveiler':'Councillor Neil Taggart, Lord Mayor of Leeds',
'date':'27 Mar 2004',
'sponser':'Middleton Railway Trust',
'easting':0,
'northing':0,
'caption':''
},
{
'id':88,
'title':'Denison Hall',
'location':'Hanover Square, Little Woodhouse, Leeds 3',
'unveiler':'Mrs. Freda Matthews, Little Woodhouse Community Campaigner',
'date':'15 May 2004',
'sponser':'Tandridge Investments Ltd',
'easting':429140,
'northing':434058,
'caption':'The grandest house ever built in central Leeds was erected in 101 days for John Wilkinson upon inheriting the fortune of his uncle, the cloth merchant, Robert Denison. Its parkland setting reflected his desire for the country gentleman&rsquo;s lifestyle for whi'
},
{
'id':89,
'title':'Olympia Works and Robert Blackburn',
'location':'Tesco Supermarket, 361, Roundhay Road,  Leeds 8',
'unveiler':'Professor Robert Blackburn, grandson of Robert Blackburn the aviation pioneer.',
'date':'26 May 2004',
'sponser':'Philip Snaith',
'easting':0,
'northing':0,
'caption':''
},
{
'id':90,
'title':'Leeds & County Liberal Club',
'location':'Quebecs Hotel, Quebec Street, Leeds 1',
'unveiler':'Mrs Joyce Wainwright, widow of Richard Wainwright, Liberal MP for the Colne Valley ',
'date':'13 July 2004',
'sponser':'The Wainwright family',
'easting':429773,
'northing':433474,
'caption':'From parliamentary and municipal reform in the 130&rsquo;s to 1894 the Liberal party dominated politics in Leeds. This splendid club in Welsh terracotta opened in 1891. Crowds were addressed from its balcony, &rsquo;on occasions of political excitement .&rsquo; Arhitects: '
},
{
'id':91,
'title':'The Leeds Club',
'location':'3 Albion Place, Leeds 1',
'unveiler':'Councillor Christopher Townsley, Lord Mayor of Leeds',
'date':'8 Dec 2004',
'sponser':'Mr. Bob Isle,Honorary Secretary of The Leeds Club',
'easting':430107,
'northing':433605,
'caption':'Moved here in 1852. As a prestigous gentlemen&rsquo;s club, it was the meeting place for the town&rsquo;s leading business and professional men. Its lavish classical interior included coffee, smoking and dining rooms, a billiard room, bedrooms and a ballroom. Founded'
},
{
'id':92,
'title':'Mount St Mary’s Convent, Orphanage & School ',
'location':'Mount St Mary’s Catholic High School, Ellerby Road, Leeds 9',
'unveiler':'Mrs Helen Kennally, Author of the History of the Convent, Orphanage & School Mount St Mary’s Schools Leeds 1853-2003',
'date':'26 Jan 2005',
'sponser':'Mount St Mary’s Catholic High School',
'easting':0,
'northing':0,
'caption':''
},
{
'id':93,
'title':'Headingley Hall',
'location':'Headingley Hall, 5, Shire Oak Road, Leeds 6',
'unveiler':'Councillor William S Hyde, Lord Mayor of Leeds and the Lady Mayoress, Mrs. Patricia Hyde.',
'date':'8 Jun 2005',
'sponser':'Westward Care (Yorkshire) Ltd',
'easting':0,
'northing':0,
'caption':''
},
{
'id':94,
'title':'Canal Gardens',
'location':'Canal Gardens, on the archway leading to Tropical World, Princes Avenue, Leeds 8',
'unveiler':'Mrs Marjorie Ziff, President of the Friends of Roundhay Park',
'date':'21 Jun 2005',
'sponser':'Friends of Roundhay Park',
'easting':0,
'northing':0,
'caption':''
},
{
'id':95,
'title':'Dr 19Alister’ MacKenzie',
'location':'The Corner House Club, 266 Lidgett Lane, Leeds 17',
'unveiler':'Mr. J  Olav Arnold, President of Leeds Civic Trust and playing member of Alwoodley Golf Club for over 60 years',
'date':'27 Jun 2005',
'sponser':'Jointly: Alwoodley Golf Club and Moortown Golf Club',
'easting':0,
'northing':0,
'caption':''
},
{
'id':96,
'title':'Richard Oastler',
'location':'The Wardrobe, St Peter’s Square, Leeds 9',
'unveiler':'Councillor Andrew Carter, Deputy Leader, Leeds City Council, with the assistance of pupils from Fulneck School.',
'date':'6 Sept 2005',
'sponser':'Professor Neville Rowell Vice-President, Leeds Civic Trust',
'easting':430813,
'northing':433524,
'caption':'The Factory King&rsquo; was born in St Peter&rsquo;s Square. His 1830 letter to the Leeds Mercruy about &rsquo;Yorkshire Slavery&rsquo; began the campaign to reduce the working day of factory children to ten hours. The Ten Hours Act of 1847 owed much to his persuasive writing and compelling oratory. 1789- 1861'
},
{
'id':97,
'title':'John Smeaton FRS',
'location':'On the towpath wall at Leeds Lock, Royal Armouries, Leeds 10',
'unveiler':'Mr. John McKenzie, President of the Smeatonian Society of Civil Engineers',
'date':'6 Oct 2005',
'sponser':'Smeatonian Society of Civil Engineers',
'easting':430895,
'northing':432976,
'caption':'Was born and lived at Austhorpe Lodge, Whitkirk, Leeds. He developed scientific methods to harness better the water, wind and steam power essential to the Industrial Revolution. He was consulted nationally on the design of mills, harbours, bridges and waterways, including the Aire and Calder Navigation. He was most famous for designing and building the third Eddystone Lighthouse. The creation of the Smeatonian Society  of Civil Engineers (1771) gave rise to the professional engineering institutions. 1724-1792'
},
{
'id':98,
'title':'Sir Clifford Allbutt',
'location':'Lyddon Hall, University of Leeds Campus Leeds 2',
'unveiler':'Dr John Wales MD, FRCP, retired Consultant Physician and past Chairman of the Faculty at the General Infirmary at Leeds',
'date':'7 Dec 2005',
'sponser':'The Faculty at the  General Infirmary at Leeds.',
'easting':429290,
'northing':434514,
'caption':'One of the most widely consulted physicians of his era lived here 1872-81. He was a physician at LGI 1864-84 and later Regius Professor of Physic at Cambridge. He is best known for inventing the short-stemmed clinical thermometer and revising &rsquo;The System of Medicine,&rsquo; the doctor&rsquo;s bible. 1836-1925.'
},
{
'id':99,
'title':'Leeds General Cemetery',
'location':'Gatehouse, St George’s Field, University of Leeds, Leeds 2',
'unveiler':'Dr Julie Rugg, a senior research fellow at York University and head of the Cemetery Research Group',
'date':'24 Apr 2006',
'sponser':'Mr and Mrs David Kaye',
'easting':0,
'northing':0,
'caption':'Moved here in 1852. As a prestigous gentlemen&rsquo;s club, it was the meeting place for the town&rsquo;s leading business and professional men. Its lavish classical interior included coffee, smoking and dining rooms, a billiard room, bedrooms and a ballroom. Founded'
},
{
'id':100,
'title':'Whitelocks',
'location':'Whitelocks Public House, Turks Head Yard, Off Briggate, Leeds 1',
'unveiler':'Miss  Sarah Whitelock, great great granddaughter of John Lupton Whitelock, landlord and licensee in 1867.',
'date':'23 May 2006',
'sponser':'Leeds Civic Trust ',
'easting':430196,
'northing':433529,
'caption':'Occupying a medieval Briggate burgage plot. It was first licensed as the Turk&rsquo;s Head in 1715.  Rebuilt by the Whitelock family in the 1880s, it later extended into the rom of Georgian working mens cottages. John Betjeman described it as &rsquo;the very heart of Leeds&rsquo;.'
},
{
'id':101,
'title':'Richard Bentley FRS DD',
'location':'Bentley Square, Calverley Rd, Oulton, Leeds 26',
'unveiler':'Mr Malcolm Brocklesby, Vice-Chairman of the Oulton Society',
'date':'7 Jun 2006',
'sponser':'The Oulton Society',
'easting':0,
'northing':0,
'caption':''
},
{
'id':102,
'title':'Live at Leeds',
'location':'University of Leeds Refectory, University of Leeds Campus Leeds 2',
'unveiler':'Mr. Pete Townshend and Mr. Roger Daltry, surviving members of The Who’s original line-up at their famous concert on 14th February 1970',
'date':'17 Jun 2006',
'sponser':'University of Leeds',
'easting':429332,
'northing':434599,
'caption':'Live At Leeds The University refectory is a legendary concert venue. The Who’s Performance here on 14th February was recorded and released as 19Live at Leeds,’ the most celebrated live album of its’ generation.'
},
{
'id':103,
'title':'The Leeds Rifles',
'location':'Carlton Barracks, Carlton  Lane, Leeds 7',
'unveiler':'Dr. Ingrid Roscoe, HM Lord Lieutenant for West Yorkshire',
'date':'8 Nov 2006',
'sponser':'Reserve forces and Cadets Association for Yorkshire and the Humber',
'easting':0,
'northing':0,
'caption':''
},
{
'id':104,
'title':'Leeds Co-operative Society',
'location':'Gatepost at entrance to Leodis Court (opp. Temple Mill)',
'unveiler':'David Schofield, past President of the Leeds Co-operative Society',
'date':'01-Mar-07',
'sponser':'Leeds Co-operative Society',
'easting':429585,
'northing':432735,
'caption':'Was founded in 1847 when workers at Holbeck&rsquo;s Benyon and Co flax-spinning mill initiated the raising of funds in instalments from working-class families to rent a mill on this site. &rsquo;The People&rsquo;s Mill&rsquo; provided them with wholesome reasonably-prices flour. By 2007, co-operatives have spread worldwide with 700 million members - but Leeds Co-operative Society was still the oldest in existence.'
},
{
'id':105,
'title':'Leonora Cohen JP OBE',
'location':'2 Claremont Villas, Clarendon Road, LS3',
'unveiler':'Michael Meadowcroft, Chairman of the Electoral Reform Society 1989-1993',
'date':'06-Jun-07',
'sponser':'Various individual sponsors',
'easting':429263,
'northing':434072,
'caption':'Leading Suffragette famous for smashing a showcase in the Jewel House at the Tower of London and for her hunger strike at Armley Gaol in 1913. Lived here between 1923-1936. Lived 1873-1978'
},
{
'id':106,
'title':'J & H McLaren’s Midland Engine Works',
'location':'Equinox Designs Ltd, 100 Jack Lane, Hunslet, LS10',
'unveiler':'The Lord Mayor of Leeds, Councillor Brian Cleasby',
'date':'17-Jun-07',
'sponser':'The Leeds & District Traction Engine Club',
'easting':0,
'northing':0,
'caption':''
},
{
'id':107,
'title':'The Leeds Library',
'location':'18 Commercial Street, Leeds,  LS1  6AL',
'unveiler':'Deputy Lord Mayor of Leeds, Councillor Alan Taylor',
'date':'06-Sep-07',
'sponser':'Member of the Library remaining anonymous.',
'easting':430104,
'northing':433552,
'caption':'A proprietary subscription library founded in 1768 with Joseph Priestley as secretary. Since 1808 it has occupied these purpose-built premises designed by Thomas Johnson. The first floor reading room and Thomas Ambler&rsquo;s &rsquo;New Room&rsquo; extension are amongst the architectual wonders of Leeds.'
}
];

